// <auto-generated />
using System;
using System.Text.Json;
using KhuyenCong.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhuyenCong.Data.Migrations
{
    [DbContext(typeof(KhuyenCongDbContext))]
    [Migration("20260519032332_UpdateMasterData")]
    partial class UpdateMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhuyenCong.Core.Entities.ChiTieuKPI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ThongKeHieuQua")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId")
                        .IsUnique();

                    b.ToTable("ChiTieuKPIs");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DonViThiCongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DonViThuHuongId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("HoSoDinhKem")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("KinhPhiDuKien")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LinhVucId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiDeAn")
                        .HasColumnType("integer");

                    b.Property<string>("MaDeAn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenDeAn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonViThiCongId");

                    b.HasIndex("DonViThuHuongId");

                    b.HasIndex("LinhVucId");

                    b.ToTable("DeAns");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<int>("LoaiDonVi")
                        .HasColumnType("integer");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("text");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaTinh")
                        .HasColumnType("text");

                    b.Property<string>("MaXa")
                        .HasColumnType("text");

                    b.Property<string>("QuyMo")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DonVis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiaChi = "Hà Nội",
                            LoaiDonVi = 4,
                            MaSoThue = "0101010101",
                            TenDonVi = "Trung tâm Khuyến công Quốc gia"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.GiaiNgan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ChungTuDinhKem")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiGiaiNgan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGiaiNgan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.ToTable("GiaiNgans");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LichSuThaoTac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TrangThaiCu")
                        .HasColumnType("integer");

                    b.Property<int?>("TrangThaiMoi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichSuThaoTacs");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LinhVuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DinhMucHoTroMax")
                        .HasColumnType("numeric");

                    b.Property<string>("MaLinhVuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LinhVucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "DAOTAO",
                            MoTa = "Hỗ trợ đào tạo nghề, truyền nghề cho lao động nông thôn",
                            TenLinhVuc = "Đào tạo nghề, truyền nghề và phát triển nhân lực"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "CONGNGHE",
                            MoTa = "Hỗ trợ đầu tư máy móc thiết bị tiên tiến vào sản xuất",
                            TenLinhVuc = "Xây dựng mô hình trình diễn kỹ thuật, chuyển giao công nghệ và ứng dụng máy móc"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "SANPHAM",
                            MoTa = "Tổ chức bình chọn, hỗ trợ phát triển sản phẩm OCOP, tiêu biểu",
                            TenLinhVuc = "Phát triển sản phẩm công nghiệp nông thôn tiêu biểu"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "LIENKET",
                            MoTa = "Tư vấn thiết kế mẫu mã, bao bì, quản lý doanh nghiệp",
                            TenLinhVuc = "Tư vấn, trợ giúp các cơ sở CNNT"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "HOICHО",
                            MoTa = "Hỗ trợ thuê gian hàng hội chợ, quảng bá sản phẩm CNNT",
                            TenLinhVuc = "Hỗ trợ cung cấp thông tin, triển lãm, hội chợ, quảng bá sản phẩm"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "QUANLY",
                            MoTa = "Tổ chức tham quan, học tập kinh nghiệm trong và ngoài nước",
                            TenLinhVuc = "Nâng cao năng lực quản lý cho các cơ sở CNNT"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "CUMCN",
                            MoTa = "Đầu tư xây dựng hạ tầng kỹ thuật cụm công nghiệp nông thôn",
                            TenLinhVuc = "Hỗ trợ phát triển hạ tầng cụm công nghiệp"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "TUVAN",
                            MoTa = "Nâng cao năng lực cho đội ngũ cộng tác viên khuyến công",
                            TenLinhVuc = "Phát triển hoạt động tư vấn khuyến công"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "KHAC",
                            MoTa = "Các nội dung hỗ trợ khác theo quy định của Chính phủ",
                            TenLinhVuc = "Các chương trình khuyến công khác"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DonViId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonViId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            PasswordHash = "admin@123",
                            Role = 4,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.SanPhamOcop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonViId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NgayCongNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhanHangSao")
                        .HasColumnType("integer");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("SanPhamOcops");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.TienDoThucHien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("FileBaoCao")
                        .HasColumnType("jsonb");

                    b.Property<string>("GhiChuThucTe")
                        .HasColumnType("text");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThangBaoCao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.ToTable("TienDoThucHiens");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.VanBanPhapLuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoKyHieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<string>("TrichYeu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VanBanPhapLuats");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.ChiTieuKPI", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithOne("ChiTieuKPI")
                        .HasForeignKey("KhuyenCong.Core.Entities.ChiTieuKPI", "DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonViThiCong")
                        .WithMany("DeAnThiCongs")
                        .HasForeignKey("DonViThiCongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonViThuHuong")
                        .WithMany("DeAnThuHuongs")
                        .HasForeignKey("DonViThuHuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhuyenCong.Core.Entities.LinhVuc", "LinhVuc")
                        .WithMany("DeAns")
                        .HasForeignKey("LinhVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViThiCong");

                    b.Navigation("DonViThuHuong");

                    b.Navigation("LinhVuc");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.GiaiNgan", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("GiaiNgans")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LichSuThaoTac", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("LichSuThaoTacs")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KhuyenCong.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.NguoiDung", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonVi")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.SanPhamOcop", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonVi")
                        .WithMany("SanPhamOcops")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.TienDoThucHien", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("TienDoThucHiens")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.Navigation("ChiTieuKPI");

                    b.Navigation("GiaiNgans");

                    b.Navigation("LichSuThaoTacs");

                    b.Navigation("TienDoThucHiens");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DonVi", b =>
                {
                    b.Navigation("DeAnThiCongs");

                    b.Navigation("DeAnThuHuongs");

                    b.Navigation("NguoiDungs");

                    b.Navigation("SanPhamOcops");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LinhVuc", b =>
                {
                    b.Navigation("DeAns");
                });
#pragma warning restore 612, 618
        }
    }
}
