// <auto-generated />
using System;
using System.Text.Json;
using KhuyenCong.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhuyenCong.Data.Migrations
{
    [DbContext(typeof(KhuyenCongDbContext))]
    [Migration("20260605023328_Update_DbSeeder_Passwords_To_BCrypt")]
    partial class Update_DbSeeder_Passwords_To_BCrypt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhuyenCong.Core.Entities.ChiTieuKPI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ThongKeHieuQua")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId")
                        .IsUnique();

                    b.ToTable("ChiTieuKPIs");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("BienBanGiamSat")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("BienBanNghiemThu")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("text");

                    b.Property<Guid?>("DonViGiamSatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DonViThiCongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DonViThuHuongId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("HoSoDinhKem")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("KinhPhiDuKien")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LinhVucId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoaiDeAnId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaDeAn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayNghiemThu")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguonKinhPhi")
                        .HasColumnType("integer");

                    b.Property<string>("TenDeAn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThoiGianGiamSat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonViGiamSatId");

                    b.HasIndex("DonViThiCongId");

                    b.HasIndex("DonViThuHuongId");

                    b.HasIndex("LinhVucId");

                    b.HasIndex("LoaiDeAnId");

                    b.ToTable("DeAns");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<double?>("KinhDo")
                        .HasColumnType("double precision");

                    b.Property<int>("LoaiDonVi")
                        .HasColumnType("integer");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("text");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaTinh")
                        .HasColumnType("text");

                    b.Property<string>("MaXa")
                        .HasColumnType("text");

                    b.Property<string>("QuyMo")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ViDo")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("DonVis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiaChi = "Hà Nội",
                            LoaiDonVi = 4,
                            MaSoThue = "0101010101",
                            TenDonVi = "Trung tâm Khuyến công Quốc gia"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiaChi = "Tỉnh/TP",
                            LoaiDonVi = 4,
                            MaSoThue = "0202020202",
                            TenDonVi = "Sở Công Thương"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.GiaiNgan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ChungTuDinhKem")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiGiaiNgan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGiaiNgan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.ToTable("GiaiNgans");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LichSuThaoTac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TrangThaiCu")
                        .HasColumnType("integer");

                    b.Property<int?>("TrangThaiMoi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LichSuThaoTacs");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LinhVuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DinhMucHoTroMax")
                        .HasColumnType("numeric");

                    b.Property<string>("MaLinhVuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LinhVucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "DAOTAO",
                            MoTa = "Hỗ trợ đào tạo nghề, truyền nghề cho lao động nông thôn",
                            TenLinhVuc = "Đào tạo nghề, truyền nghề và phát triển nhân lực"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "CONGNGHE",
                            MoTa = "Hỗ trợ đầu tư máy móc thiết bị tiên tiến vào sản xuất",
                            TenLinhVuc = "Xây dựng mô hình trình diễn kỹ thuật, chuyển giao công nghệ và ứng dụng máy móc"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "SANPHAM",
                            MoTa = "Tổ chức bình chọn, hỗ trợ phát triển sản phẩm OCOP, tiêu biểu",
                            TenLinhVuc = "Phát triển sản phẩm công nghiệp nông thôn tiêu biểu"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "LIENKET",
                            MoTa = "Tư vấn thiết kế mẫu mã, bao bì, quản lý doanh nghiệp",
                            TenLinhVuc = "Tư vấn, trợ giúp các cơ sở CNNT"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "HOICHО",
                            MoTa = "Hỗ trợ thuê gian hàng hội chợ, quảng bá sản phẩm CNNT",
                            TenLinhVuc = "Hỗ trợ cung cấp thông tin, triển lãm, hội chợ, quảng bá sản phẩm"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "QUANLY",
                            MoTa = "Tổ chức tham quan, học tập kinh nghiệm trong và ngoài nước",
                            TenLinhVuc = "Nâng cao năng lực quản lý cho các cơ sở CNNT"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "CUMCN",
                            MoTa = "Đầu tư xây dựng hạ tầng kỹ thuật cụm công nghiệp nông thôn",
                            TenLinhVuc = "Hỗ trợ phát triển hạ tầng cụm công nghiệp"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "TUVAN",
                            MoTa = "Nâng cao năng lực cho đội ngũ cộng tác viên khuyến công",
                            TenLinhVuc = "Phát triển hoạt động tư vấn khuyến công"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaLinhVuc = "KHAC",
                            MoTa = "Các nội dung hỗ trợ khác theo quy định của Chính phủ",
                            TenLinhVuc = "Các chương trình khuyến công khác"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LoaiDeAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoaiDeAns");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DonViId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonViId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            PasswordHash = "$2a$11$PlXjHmRvDP47AePRB6F2Uu.cfUqOXiiS5k7Qotxt/apiK4ST2BJ52",
                            Role = 4,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonViId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            PasswordHash = "$2a$11$MXxcVGaKDj9GsoWlWkIAzOM1a/OIEyR9DvhX3Jd20fCPofvFZl75u",
                            Role = 2,
                            Username = "canboso"
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.SanPhamOcop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapChungNhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonViId")
                        .HasColumnType("uuid");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<int>("LoaiSanPham")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int?>("NamBinhChon")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCongNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhanHangSao")
                        .HasColumnType("integer");

                    b.Property<string>("QuyetDinhCongNhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("SanPhamOcops");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.TienDoThucHien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeAnId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("FileBaoCao")
                        .HasColumnType("jsonb");

                    b.Property<string>("GhiChuThucTe")
                        .HasColumnType("text");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThangBaoCao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeAnId");

                    b.ToTable("TienDoThucHiens");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.TinTuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TinTucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Category = "Thông báo",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Cục Công Thương địa phương thông báo tới các Sở Công Thương về việc phê duyệt danh mục các đề án khuyến công điểm và đề án nhóm thuộc Chương trình khuyến công quốc gia.",
                            IsHot = true,
                            PublishedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Quyết định phê duyệt danh mục đề án khuyến công quốc gia năm 2026",
                            Views = 1240
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Category = "Chính sách",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Nhằm thúc đẩy phát triển kinh tế địa phương, Bộ Công Thương ban hành chính sách hỗ trợ đặc biệt dành cho các doanh nghiệp vừa và nhỏ tham gia chương trình khuyến công.",
                            IsHot = true,
                            PublishedAt = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Chính sách hỗ trợ doanh nghiệp nhỏ và vừa trong lĩnh vực công nghiệp nông thôn",
                            Views = 876
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Category = "Sự kiện",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Hội nghị sẽ diễn ra tại Hà Nội vào ngày 25/05/2026, tổng kết những thành tích nổi bật và định hướng phát triển cho giai đoạn 2026–2030 của Chương trình Khuyến công.",
                            IsHot = false,
                            PublishedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Hội nghị tổng kết Chương trình Khuyến công Quốc gia giai đoạn 2021–2025",
                            Views = 512
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Category = "Quyết định",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Thông tư số 05/2026/TT-BCT quy định chi tiết về quy trình lập dự toán, phân bổ, quản lý và quyết toán kinh phí thực hiện các hoạt động khuyến công quốc gia.",
                            IsHot = false,
                            PublishedAt = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Ban hành Thông tư hướng dẫn quản lý, sử dụng kinh phí khuyến công quốc gia",
                            Views = 398
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            Category = "Hướng dẫn",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Để tạo thuận lợi cho các tổ chức, cá nhân, Cục Công Thương địa phương hướng dẫn chi tiết quy trình nộp hồ sơ đề án khuyến công trực tuyến qua hệ thống.",
                            IsHot = false,
                            PublishedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Hướng dẫn nộp hồ sơ đề án khuyến công trực tuyến trên Cổng thông tin điện tử",
                            Views = 721
                        },
                        new
                        {
                            Id = new Guid("c6666666-6666-6666-6666-666666666666"),
                            Category = "Thông báo",
                            Content = "",
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Cục Công Thương địa phương thông báo thời gian tiếp nhận hồ sơ đề án khuyến công quốc gia đợt 2 năm 2026 bắt đầu từ ngày 01/06/2026 đến 30/06/2026.",
                            IsHot = false,
                            PublishedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Thông báo lịch tiếp nhận hồ sơ khuyến công quốc gia đợt 2 năm 2026",
                            Views = 289
                        });
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.VanBanPhapLuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("text");

                    b.Property<int>("LoaiTaiLieu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiKy")
                        .HasColumnType("text");

                    b.Property<string>("SoKyHieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<string>("TrichYeu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VanBanPhapLuats");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.ChiTieuKPI", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithOne("ChiTieuKPI")
                        .HasForeignKey("KhuyenCong.Core.Entities.ChiTieuKPI", "DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonViGiamSat")
                        .WithMany()
                        .HasForeignKey("DonViGiamSatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonViThiCong")
                        .WithMany("DeAnThiCongs")
                        .HasForeignKey("DonViThiCongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonViThuHuong")
                        .WithMany("DeAnThuHuongs")
                        .HasForeignKey("DonViThuHuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhuyenCong.Core.Entities.LinhVuc", "LinhVuc")
                        .WithMany("DeAns")
                        .HasForeignKey("LinhVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhuyenCong.Core.Entities.LoaiDeAn", "LoaiDeAn")
                        .WithMany("DeAns")
                        .HasForeignKey("LoaiDeAnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViGiamSat");

                    b.Navigation("DonViThiCong");

                    b.Navigation("DonViThuHuong");

                    b.Navigation("LinhVuc");

                    b.Navigation("LoaiDeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.GiaiNgan", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("GiaiNgans")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LichSuThaoTac", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("LichSuThaoTacs")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KhuyenCong.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.NguoiDung", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonVi")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.SanPhamOcop", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DonVi", "DonVi")
                        .WithMany("SanPhamOcops")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.TienDoThucHien", b =>
                {
                    b.HasOne("KhuyenCong.Core.Entities.DeAn", "DeAn")
                        .WithMany("TienDoThucHiens")
                        .HasForeignKey("DeAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeAn");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DeAn", b =>
                {
                    b.Navigation("ChiTieuKPI");

                    b.Navigation("GiaiNgans");

                    b.Navigation("LichSuThaoTacs");

                    b.Navigation("TienDoThucHiens");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.DonVi", b =>
                {
                    b.Navigation("DeAnThiCongs");

                    b.Navigation("DeAnThuHuongs");

                    b.Navigation("NguoiDungs");

                    b.Navigation("SanPhamOcops");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LinhVuc", b =>
                {
                    b.Navigation("DeAns");
                });

            modelBuilder.Entity("KhuyenCong.Core.Entities.LoaiDeAn", b =>
                {
                    b.Navigation("DeAns");
                });
#pragma warning restore 612, 618
        }
    }
}
